AllCops:
  NewCops: enable
  Exclude:
    - "brew/**/*"
    - "tmux/plugins/**/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Max: 99

Layout/LineLength:
  Max: 200
