AllCops:
  NewCops: enable
  Exclude:
    - "brew/Brewfile"
    - "tmux/plugins/tpm/lib/tmux-test/Vagrantfile"
    - "tmux/plugins/tmux-yank/Vagrantfile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Max: 99

Layout/LineLength:
  Max: 200
