[aws]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 10
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[$symbol$branch]($style) "
# symbol = "🍣 "
style = "bold green"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

# [git_status]
# conflicted = "⚔️ "
# ahead = "🏎️ 💨 ×${count}"
# behind = "🐢 ×${count}"
# diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
# untracked = "🛤️  ×${count}"
# stashed = "📦 "
# modified = "📝 ×${count}"
# staged = "🗃️  ×${count}"
# renamed = "📛 ×${count}"
# deleted = "🗑️  ×${count}"
# style = "bright-white"
# format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
# trim_at = "-"
style = "bold dimmed white"
# disabled = false

[username]
style_user = "bold dimmed white"
format = '[$user]($style)@'
show_always = true
