#!/bin/zsh

##? dotenv - Load a .env file for a project
##?
##? usage: dotenv

#function dotenv() {
# Loads a .env file from the cwd if one exists
if [ -f ".env" ]; then
  set -o allexport
  source .env
  set +o allexport
fi
#}
