return {}
--   "saghen/blink.cmp",
--   opts = {
--     keymap = {
--       preset = "super-tab",
--     },
--     enabled = function()
--       local disabled = false
--       disabled = disabled or (vim.tbl_contains({ "markdown" }, vim.bo.filetype))
--       disabled = disabled or (vim.bo.buftype == "prompt")
--       disabled = disabled or (vim.fn.reg_recording() ~= "")
--       disabled = disabled or (vim.fn.reg_executing() ~= "")
--       return not disabled
--     end,
--   },
-- }
