# each worktree opens as a seperate session as opposed to windows
mode: session
# don't add dagent icons to tmux windows
# status_format: false
# enable nerd fonts, duh
nerdfont: true
# default agent
agent: claude

# auto-naming is automatic when agent is configured
# auto_name:
#   background: true # Always run in background when using --auto-name

# default window layout
windows:
  # - name: editor
  #   panes:
  #     - command: nvim
  - name: agent
    panes:
      - command: claude --permission-mode auto
        focus: true
  - name: shell
