# Tokyo Night (Night) Theme
# Matches https://github.com/folke/tokyonight.nvim

set -g mode-style "fg=#7aa2f7,bg=#292e42"

set -g message-style "fg=#7aa2f7,bg=#292e42"
set -g message-command-style "fg=#7aa2f7,bg=#292e42"

set -g pane-border-style "fg=#292e42"
set -g pane-active-border-style "fg=#7aa2f7"

# Active pane is dark (bg_dark), inactive panes are slightly lighter (bg)
set -g window-active-style "bg=#16161e"
set -g window-style "bg=#1a1b26"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=#7aa2f7,bg=#16161e"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#{?pane_in_mode,#[fg=#16161e]#[bg=#e0af68]#[bold] [C] #[fg=#e0af68]#[bg=#16161e]#[nobold],#[fg=#16161e]#[bg=#9ece6a]#[bold] [N] #[fg=#9ece6a]#[bg=#16161e]#[nobold]}#[fg=#16161e]#[bg=#7aa2f7]#[bold] #S #[fg=#7aa2f7]#[bg=#16161e]#[nobold]"
set -g status-right "#($SCOUT_DIR/scripts/status-widget.sh)#[fg=#7aa2f7]#[bg=#16161e] #{prefix_highlight}#(~/.config/tmux/battery.sh)#[fg=#7aa2f7]#[bg=#292e42] %Y-%m-%d  %I:%M %p #[fg=#292e42]#[bg=#16161e]#[fg=#16161e]#[bg=#7aa2f7]#[bold] #U@#H "
if-shell '[ "$(tmux show-option -gqv \"clock-mode-style\")" == "24" ]' {
  set -g status-right "#($SCOUT_DIR/scripts/status-widget.sh)#[fg=#7aa2f7]#[bg=#16161e] #{prefix_highlight}#(~/.config/tmux/battery.sh)#[fg=#7aa2f7]#[bg=#292e42] %Y-%m-%d  %H:%M #[fg=#292e42]#[bg=#16161e]#[fg=#16161e]#[bg=#7aa2f7]#[bold] #U@#H "
}

setw -g window-status-activity-style "underscore,fg=#c0caf5,bg=#16161e"
setw -g window-status-separator " "
setw -g window-status-style "NONE,fg=#c0caf5,bg=#16161e"
setw -g window-status-format " #I  #W #F "
setw -g window-status-current-format "#[fg=#16161e]#[bg=#bb9af7]#[bold] #I  #W #F #[fg=#bb9af7]#[bg=#16161e]#[nobold]"

# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "#[fg=#16161e]#[bg=#e0af68]#[bold] "
set -g @prefix_highlight_output_suffix " #[fg=#e0af68]#[bg=#16161e]#[nobold]"
