autoload -Uz compinit
compinit

for config (~/Development/dotfiles/zsh/lib/*.zsh) source $config

if [[ -f "${HOME}/.zsh_local" ]]; then
  source "${HOME}/.zsh_local"
fi

# If chruby, set a default ruby so we're not using system ruby
if _has chruby-exec; then
  chruby 2.4
fi
