#!/usr/bin/env bash

##############################################################
# Bootstrap my work environment
##############################################################

# Set my editor and git editor
export EDITOR=vim
export GIT_EDITOR=vim

# Defining this here as well as bashrc because of the way I use iTerm
# to load different shells.
pathadd() { case ":${PATH:=$1}:" in *:"$1":*) ;; *) PATH="$1:$PATH" ;; esac }

# ~/.local support
pathadd "${HOME}/.local/bin"

alias gpoh='git push origin HEAD'
alias brake='bundle exec rake'

source ~/src/dotfiles/bash/aliases

if type asdf >/dev/null; then
  # Find where asdf should be installed
  ASDF_DATA_DIR="${ASDF_DATA_DIR:-$HOME/.asdf}"

  # For golang compatibility
  export ASDF_GOLANG_MOD_VERSION_ENABLED=true

  path=("$ASDF_DATA_DIR/shims" "$path[@]")
fi

# if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
#   eval "$(oh-my-posh init bash --config ${HOME}/.config/ohmyposh/ohmyposh.json)"
# fi
source ~/src/dotfiles/bash/colors.theme.bash
source ~/src/dotfiles/bash/pure.theme.bash

# Localized setup
if [[ -f "${HOME}/.bash_local" ]]; then
  source "${HOME}/.bash_local"
fi
if [[ -f "${HOME}/.secrets" ]]; then
  source "${HOME}/.secrets"
fi

# Bat: https://github.com/sharkdp/bat#configuration-file
export BAT_CONFIG_PATH="~/src/dotfiles/bat/bat.conf"

# Opt out of Homebrew analytics
export HOMEBREW_NO_ANALYTICS=1
# Cleanup on install
export HOMEBREW_INSTALL_CLEANUP=1
# Cask options
# export HOMEBREW_CASK_OPTS="--appdir=~/Applications"

#export GOROOT=/usr/local/opt/go/libexec
export PATH
