#!/usr/bin/env bash

##############################################################
# Bootstrap my work environment
if [[ -d "$HOME/Development" ]]; then
  SQUARE_HOME=$HOME/Development
fi
export SQUARE_HOME
if [[ -f "$SQUARE_HOME/config_files/square/bash_profile" ]]; then
  source $SQUARE_HOME/config_files/square/bash_profile
else
  alias _pair_startup=true
fi
##############################################################


# Set my editor and git editor
export EDITOR=vim
export GIT_EDITOR=vim

# Configure the current git user on shell startup.
_pair_startup

# Print the current git author when the shell loads
if [[ -n $(which git) ]]; then
  printf "${COLOR_LIGHT_CYAN}Current git author:${COLOR_WHITE} ${GIT_AUTHOR_NAME:-$(git config user.name)} <${GIT_AUTHOR_EMAIL:-$(git config user.email)}>\n${COLOR_NC}"
fi

source ~/code/dotfiles/bash/base.theme.bash
source ~/code/dotfiles/bash/colors.theme.bash
source ~/code/dotfiles/bash/ianc.theme.bash

if [[ -f "/usr/local/etc/bash_completion" ]]; then
  source /usr/local/etc/bash_completion
fi

if [[ -d "/usr/local/opt/go/libexec/" ]]; then
  export GOROOT=/usr/local/opt/go/libexec/
fi

alias gpoh='git push origin HEAD'
alias brake='bundle exec rake'

# vim: filetype=sh
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/opt/go/libexec//bin:$PATH
