########################################################
# Bootstrap my work environment
if [[ -f "$SQUARE_HOME/config_files/square/bashrc" ]]; then
  source $SQUARE_HOME/config_files/square/bashrc
fi
########################################################


alias vim-update-plugins='vim +PluginInstall +qall'

pathadd() {
  if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
    PATH="${PATH:+"$PATH:"}$1"
  fi
}

pathadd /usr/local/bin
export PATH

