name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruby-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --display-cop-names --color

  shell-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./bootstrap"
          format: gcc
          severity: warning

  config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate YAML files
        run: |
          find . -not -path "./tmux/plugins/*" \( -name "*.yml" -o -name "*.yaml" \) | xargs -I {} sh -c 'echo "Checking {}" && python3 -c "import yaml; yaml.safe_load(open(\"{}\"))"'

      # - name: Validate JSON files
      #   run: |
      #     find . -name "*.json" | xargs -I {} sh -c 'echo "Checking {}" && python3 -m json.tool {} > /dev/null'

      - name: Validate TOML files
        run: |
          pip install toml
          find . -not -path "./tmux/plugins/*" -name "*.toml" | xargs -I {} sh -c 'echo "Checking {}" && python3 -c "import toml; toml.load(\"{}\")"'

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
